name: 🗳️ Docker Build & Push

on:
  release:
    types: [published]
  push:
    tags:
      - "school-web@*"
      - "school-api@*"

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v2

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🪪 Get tag name
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: 🪴 Extract service name
        id: extract_service_name
        run: echo ::set-output name=service_name::${{ steps.get_tag.outputs.tag | split('@')[0] }}

      - name: 💭 Get service version
        id: get_service_version
        run: echo ::set-output name=service_version::${{ steps.get_tag.outputs.tag | split('@')[1] }}

      - name: 🏗️ Docker Build & Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          SERVICE_NAME=$(echo ${{ steps.extract_service_name.outputs.service_name }})
          SERVICE_VERSION=$(echo ${{ steps.get_service_version.outputs.service_version }})
          docker build . --target $SERVICE_NAME --tag $SERVICE_NAME:$SERVICE_VERSION
          docker tag $SERVICE_NAME:$SERVICE_VERSION $DOCKER_USERNAME/$SERVICE_NAME:$SERVICE_VERSION
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $SERVICE_NAME $DOCKER_USERNAME/$SERVICE_NAME:$SERVICE_VERSION
